name: 'deploy-main'
run-name: '${{ github.actor }} is Deploy MAIN branch'

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: |- 
          gcloud info
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v2'
        with:
          driver-opts: 'network=host'

      - name: 'Login to GCR'
        uses: 'docker/login-action@v2'
        with:
          registry: 'asia.gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: 'Build and push'
        uses: 'docker/build-push-action@v4'
        with:
          context: '.'
          file: './docker/Dockerfile'
          push: 'true'
          tags: 'asia-northeast3-docker.pkg.dev/mundeuk/mundeuk-be-proto/latest'
          cache-from: 'type=gha'
          cache-to: 'type=gha,mode=max'

  deploy:
    needs:
      - 'build'
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'ns-viral-point-server'
          region: 'asia-northeast3'
          image: 'asia-northeast3-docker.pkg.dev/mundeuk/mundeuk-be-proto/latest'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
